apiVersion: v1
kind: Service
metadata:
  name: urltools-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: url-tools-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80