apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-tools-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-tools
  template:
    metadata:
      labels:
        app: url-tools
    spec:
      containers:
        - name: urltools
          image: ghcr.io/neltarim/urltools:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-admin