name: test

on:
  pull_request:
    branches:
    - master

jobs: 
  check_possibilities:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name : git diff
      run : git diff
